
module.exports = {
    "andhra_pradesh": "AP",
    "arunachal_pradesh": "AR",
    "assam": "AS",
    "bihar": "BR",
    "chhattisgarh": "CG",
    "goa": "GA",
    "gujarat": "GJ",
    "haryana": "HR",
    "himachal_pradesh": "HP",
    "jharkhand": "JH",
    "karnataka": "KA",
    "kerala": "KL",
    "madhya_pradesh": "MP",
    "maharashtra": "MH",
    "manipur": "MN",
    "meghalaya": "ML",
    "mizoram": "MZ",
    "nagaland": "NL",
    "odisha": "OR",
    "punjab": "PB",
    "rajasthan": "RJ",
    "sikkim": "SK",
    "tamil_nadu": "TN",
    "telangana": "TG",
    "tripura": "TR",
    "uttarakhand": "UK",
    "uttar_pradesh": "UP",
    "west_bengal": "WB",
  };
  